baseURL = 'https://ginacheeseman.com/'
languageCode = 'en-us'
title = 'Gina Cheeseman'
defaultContentLanguage = 'en'
enableEmoji = true
theme = "hugo-coder"

[params]
author = "Gina Cheeseman"
description = "Gina Cheeseman's personal website"
keywords = "blog,developer,personal"
info = ["Full Stack Developer", "Knitter"]
avatarURL = 'images/avatar.jpg'
since = 2023
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/grcheeseman"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/gina-roscioli-cheeseman/"

[[params.social]]
name = "Medium"
icon = "fa fa-2x fa-medium"
weight = 5
url = "https://medium.com/@gmroscioli"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "Contact Me"
weight = 3
url = "contact/"